name: 🔒 Security Issue
description: Report a security vulnerability (please use private reporting for sensitive issues)
title: "[Security]: "
labels: ["security", "urgent"]
assignees: ["antowirantoIO"]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: If this is a critical security vulnerability, please consider using GitHub's private vulnerability reporting instead of creating a public issue.

        Thanks for helping us keep our project secure! 🔒

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? (This will be kept confidential)
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low - Information disclosure with minimal impact
        - Medium - Limited access or minor data exposure
        - High - Significant access or data exposure
        - Critical - Full system compromise or major data breach
    validations:
      required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication Bypass
        - Authorization Issues
        - SQL Injection
        - XSS (Cross-Site Scripting)
        - CSRF (Cross-Site Request Forgery)
        - Information Disclosure
        - Code Injection
        - Path Traversal
        - Insecure Direct Object Reference
        - Security Misconfiguration
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability in detail
      placeholder: The application is vulnerable to...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
      placeholder: An attacker could...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this security issue? (Be careful not to include actual exploit code)
      placeholder: |
        1. Navigate to...
        2. Enter malicious input...
        3. Observe the vulnerability
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: If applicable, provide a safe proof of concept (avoid actual exploits)
      placeholder: Provide evidence of the vulnerability without causing harm
    validations:
      required: false

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected by this vulnerability?
      placeholder: |
        - Version 1.0.0: Affected
        - Version 0.9.0: Not affected
    validations:
      required: false

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: If you have suggestions on how to fix this vulnerability, please share them
      placeholder: This could be fixed by...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. macOS 12.0, Windows 11]
        - Browser: [e.g. Chrome 91.0, Safari 14.1]
        - Application version: [e.g. 1.0.0]
    validations:
      required: false

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: Responsible Disclosure
      description: Security reporting guidelines
      options:
        - label: I understand this issue will be handled confidentially until a fix is available
          required: true
        - label: I have not publicly disclosed this vulnerability elsewhere
          required: true
        - label: I agree to follow responsible disclosure practices
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/antowirantoIO/nextjs-enterprise-crm/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true